//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;


namespace AssemblyCSharp
{
	public class NameGenerator
	{
		private string[] maleNames;
		private string[] femaleNames;
		private string[] lastNames;


		private static NameGenerator instance;
		private NameGenerator() {}
		
		public static NameGenerator Instance
		{
			get 
			{
				if (instance == null)
				{
					instance = new NameGenerator();
					instance.loadNames("MaleNames", out instance.maleNames);
					instance.loadNames("FemaleNames", out instance.femaleNames);
					instance.loadNames("LastNames", out instance.lastNames);
				}
				return instance;
			}
		}

		private void loadNames(string file, out string[] names)
		{
			TextAsset bindata = Resources.Load(file) as TextAsset;
			string namesString = bindata.ToString();
			Resources.UnloadAsset(bindata);
			names = namesString.Split('\n');
		}

		public string getRandomName(char gender)
		{
			var firstName = gender == 'm' ? getRandomNameFromList(maleNames) : getRandomNameFromList(femaleNames);
			var lastName = getRandomNameFromList(lastNames);

			return firstName + " " + lastName;
		}

		public string getRandomNameFromList(string[] names)
		{
			return names[UnityEngine.Random.Range(0, names.Length)];
		}
	}
}

